 var fruits=["Apple","Banana"];
   fruits.splice(1,0,"pineapple");
   fruits.splice(2,0,"Orange");
   fruits.splice(3,0,"strawberry");
   fruits.splice(4,0,"mango");
   fruits.splice(5,0,"jack");
 document.write(fruits+"<br>");
document.write("fruit name in 3rd index : "+fruits[3]+"<br>");
document.write(fruits.length +"<br>");
document.write(fruits.reverse());
